apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: frr-k8s
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: frr-k8s-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: frr-k8s
    app.kubernetes.io/part-of: frr-k8s
    app.kubernetes.io/managed-by: kustomize
  name: metrics-service
  namespace: system
spec:
  ports:
  - name: metricshttps
    port: 9140
    targetPort: metricshttps
  - name: frrmetricshttps
    port: 9141
    targetPort: frrmetricshttps
  selector:
    control-plane: frr-k8s
